CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE schema_meta (
    key text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE machines (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_seen_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE contributors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contributor_key text NOT NULL UNIQUE,
    display_name text NOT NULL,
    email text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE contributor_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id uuid NOT NULL REFERENCES machines(id),
    contributor_id bigint NOT NULL REFERENCES contributors(id),
    path_prefix text,
    provider text,
    effective_from timestamptz NOT NULL DEFAULT '-infinity',
    effective_to timestamptz NOT NULL DEFAULT 'infinity',
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (effective_from < effective_to)
);

CREATE TABLE sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id uuid NOT NULL REFERENCES machines(id),
    provider text NOT NULL,
    path text NOT NULL,
    source_kind text NOT NULL,
    active_revision_id bigint,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (machine_id, provider, source_kind, path)
);

CREATE TABLE source_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES sources(id),
    revision_no integer NOT NULL,
    size_bytes bigint NOT NULL DEFAULT 0,
    mtime_ns bigint NOT NULL DEFAULT 0,
    device bigint,
    inode bigint,
    head_hash text,
    checkpoint_hash text,
    aggregate_hash text,
    ingested_offset bigint NOT NULL DEFAULT 0,
    ingested_lines bigint NOT NULL DEFAULT 0,
    pending_offset bigint,
    pending_length bigint NOT NULL DEFAULT 0,
    pending_hash text,
    parser_version integer NOT NULL DEFAULT 1,
    status text NOT NULL DEFAULT 'pending',
    error_count bigint NOT NULL DEFAULT 0,
    last_error text,
    started_at timestamptz,
    completed_at timestamptz,
    closed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (source_id, revision_no),
    CHECK (status IN ('pending', 'ingesting', 'partial', 'complete', 'failed', 'replaced', 'truncated')),
    CHECK (ingested_offset >= 0 AND ingested_lines >= 0 AND pending_length >= 0)
);

ALTER TABLE sources
ADD CONSTRAINT sources_active_revision_fk
FOREIGN KEY (active_revision_id) REFERENCES source_revisions(id) DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX source_revisions_source_status_idx ON source_revisions(source_id, status);
CREATE INDEX sources_provider_kind_idx ON sources(provider, source_kind);
CREATE INDEX sources_path_trgm_idx ON sources USING gin(path gin_trgm_ops);

CREATE TABLE raw_payloads (
    payload_hash text PRIMARY KEY,
    payload bytea NOT NULL,
    byte_length bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CHECK (byte_length = octet_length(payload))
);

CREATE TABLE raw_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_revision_id bigint NOT NULL REFERENCES source_revisions(id),
    line_no bigint NOT NULL,
    byte_offset bigint NOT NULL,
    byte_length bigint NOT NULL,
    payload_hash text NOT NULL REFERENCES raw_payloads(payload_hash),
    ingested_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (source_revision_id, line_no),
    UNIQUE (source_revision_id, byte_offset),
    CHECK (line_no > 0 AND byte_offset >= 0 AND byte_length > 0)
);

CREATE INDEX raw_records_payload_idx ON raw_records(payload_hash);

CREATE TABLE projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key text NOT NULL UNIQUE,
    name text NOT NULL,
    repository_url text,
    repository_host text,
    repository_owner text,
    repository_name text,
    is_unresolved boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX projects_name_trgm_idx ON projects USING gin(name gin_trgm_ops);
CREATE INDEX projects_repository_trgm_idx ON projects USING gin(repository_url gin_trgm_ops);

CREATE TABLE project_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    machine_id uuid REFERENCES machines(id),
    path_prefix text,
    provider text,
    alias text,
    effective_from timestamptz NOT NULL DEFAULT '-infinity',
    effective_to timestamptz NOT NULL DEFAULT 'infinity',
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (path_prefix IS NOT NULL OR alias IS NOT NULL),
    CHECK (effective_from < effective_to)
);

CREATE INDEX project_aliases_path_trgm_idx ON project_aliases USING gin(path_prefix gin_trgm_ops);

CREATE TABLE activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    title text NOT NULL,
    classification text NOT NULL DEFAULT 'unclassified',
    reporting_period_start date NOT NULL,
    reporting_period_end date NOT NULL,
    description text,
    uncertainty_or_hypothesis text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (classification IN ('core', 'supporting', 'non-project', 'unclassified')),
    CHECK (reporting_period_start <= reporting_period_end)
);

CREATE INDEX activities_title_trgm_idx ON activities USING gin(title gin_trgm_ops);

CREATE TABLE project_default_activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    activity_id bigint NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    effective_from timestamptz NOT NULL DEFAULT '-infinity',
    effective_to timestamptz NOT NULL DEFAULT 'infinity',
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (effective_from < effective_to),
    UNIQUE (project_id, effective_from)
);

CREATE TABLE sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key text NOT NULL UNIQUE,
    provider text NOT NULL,
    external_id text NOT NULL,
    project text,
    project_id bigint REFERENCES projects(id) ON DELETE SET NULL,
    contributor_id bigint REFERENCES contributors(id) ON DELETE SET NULL,
    machine_id uuid REFERENCES machines(id),
    cwd text,
    started_at timestamptz,
    ended_at timestamptz,
    parent_session_id text,
    model text,
    title text,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    event_count bigint NOT NULL DEFAULT 0,
    text_unit_count bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX sessions_provider_external_idx ON sessions(provider, external_id);
CREATE INDEX sessions_project_started_idx ON sessions(project_id, started_at);
CREATE INDEX sessions_project_text_trgm_idx ON sessions USING gin(project gin_trgm_ops);
CREATE INDEX sessions_cwd_trgm_idx ON sessions USING gin(cwd gin_trgm_ops);
CREATE INDEX sessions_title_trgm_idx ON sessions USING gin(title gin_trgm_ops);

CREATE TABLE session_sources (
    session_id bigint NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    source_id bigint NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    PRIMARY KEY (session_id, source_id)
);

CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key text NOT NULL UNIQUE,
    source_id bigint NOT NULL REFERENCES sources(id),
    source_revision_id bigint NOT NULL REFERENCES source_revisions(id),
    raw_record_id bigint NOT NULL UNIQUE REFERENCES raw_records(id),
    session_id bigint REFERENCES sessions(id) ON DELETE SET NULL,
    ordinal bigint NOT NULL,
    line_no bigint NOT NULL,
    byte_offset bigint NOT NULL,
    byte_length bigint NOT NULL,
    timestamp timestamptz,
    event_type text NOT NULL,
    subtype text,
    role text,
    provider_event_id text,
    parent_event_id text,
    turn_id text,
    content_hash text NOT NULL,
    event_fingerprint text,
    canonical_event_id bigint REFERENCES events(id) ON DELETE SET NULL,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    parse_error text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (source_revision_id, line_no)
);

CREATE INDEX events_session_order_idx ON events(session_id, timestamp, ordinal);
CREATE INDEX events_source_line_idx ON events(source_revision_id, line_no);
CREATE INDEX events_type_subtype_idx ON events(event_type, subtype);
CREATE INDEX events_provider_id_idx ON events(provider_event_id);
CREATE INDEX events_content_hash_idx ON events(content_hash);
CREATE INDEX events_provider_fingerprint_idx ON events(provider_event_id, event_fingerprint);

CREATE TABLE contents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_hash text NOT NULL UNIQUE,
    text text NOT NULL,
    char_count bigint NOT NULL,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, text)) STORED,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX contents_search_idx ON contents USING gin(search_vector);
CREATE INDEX contents_text_trgm_idx ON contents USING gin(text gin_trgm_ops);

CREATE TABLE text_units (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_key text NOT NULL UNIQUE,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    unit_index integer NOT NULL,
    kind text NOT NULL,
    label text,
    is_error boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (event_id, unit_index)
);

CREATE INDEX text_units_content_idx ON text_units(content_id);
CREATE INDEX text_units_kind_error_idx ON text_units(kind, is_error);

CREATE TABLE artifacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_key text NOT NULL UNIQUE,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    kind text NOT NULL,
    label text,
    value text NOT NULL,
    value_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX artifacts_kind_hash_idx ON artifacts(kind, value_hash);
CREATE INDEX artifacts_event_idx ON artifacts(event_id);
CREATE INDEX artifacts_value_trgm_idx ON artifacts USING gin(value gin_trgm_ops);

CREATE TABLE episodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_key text NOT NULL UNIQUE,
    generation text NOT NULL,
    segmentation_version integer NOT NULL,
    session_id bigint NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    sequence_no integer NOT NULL,
    first_event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    last_event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    started_at timestamptz,
    ended_at timestamptz,
    active_seconds double precision NOT NULL DEFAULT 0,
    goal_content_id bigint REFERENCES contents(id) ON DELETE SET NULL,
    outcome_content_id bigint REFERENCES contents(id) ON DELETE SET NULL,
    document_content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    event_count bigint NOT NULL DEFAULT 0,
    attempt_count bigint NOT NULL DEFAULT 0,
    error_count bigint NOT NULL DEFAULT 0,
    evidence_state text NOT NULL DEFAULT 'discussion',
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (session_id, sequence_no, generation)
);

CREATE INDEX episodes_session_sequence_idx ON episodes(session_id, sequence_no);
CREATE INDEX episodes_generation_state_idx ON episodes(generation, evidence_state);

CREATE TABLE occurrence_activity_overrides (
    episode_key text PRIMARY KEY,
    activity_id bigint NOT NULL REFERENCES activities(id),
    project_id bigint REFERENCES projects(id),
    note text,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE episode_events (
    episode_id bigint NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    position integer NOT NULL,
    section text NOT NULL,
    PRIMARY KEY (episode_id, event_id)
);

CREATE INDEX episode_events_event_idx ON episode_events(event_id);

CREATE TABLE episode_fingerprints (
    episode_id bigint NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
    kind text NOT NULL,
    value text NOT NULL,
    value_hash text NOT NULL,
    PRIMARY KEY (episode_id, kind, value_hash)
);

CREATE INDEX episode_fingerprints_lookup_idx ON episode_fingerprints(kind, value_hash, episode_id);

CREATE TABLE semantic_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key text NOT NULL UNIQUE,
    model_name text NOT NULL,
    model_revision text,
    dimensions integer NOT NULL CHECK (dimensions = 512),
    window_chars integer NOT NULL,
    overlap_events integer NOT NULL,
    profile text NOT NULL CHECK (profile IN ('conversation', 'episodes')),
    corpus_fingerprint text NOT NULL,
    derivation_version integer NOT NULL,
    status text NOT NULL CHECK (status IN ('building', 'complete', 'failed', 'stale')),
    is_active boolean NOT NULL DEFAULT false,
    config_json jsonb NOT NULL,
    expected_count bigint NOT NULL DEFAULT 0,
    chunk_count bigint NOT NULL DEFAULT 0,
    started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at timestamptz,
    error text
);

CREATE UNIQUE INDEX semantic_runs_one_active_profile_idx ON semantic_runs(profile) WHERE is_active;

CREATE TABLE semantic_windows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES semantic_runs(id) ON DELETE CASCADE,
    window_key text NOT NULL,
    session_id bigint NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    episode_id bigint REFERENCES episodes(id) ON DELETE SET NULL,
    first_event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    last_event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    sequence_no integer NOT NULL,
    content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    vector_ordinal bigint,
    embedding vector(512),
    cluster_id integer,
    projection_x double precision,
    projection_y double precision,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (run_id, window_key)
);

CREATE INDEX semantic_windows_run_vector_idx ON semantic_windows(run_id, vector_ordinal);
CREATE INDEX semantic_windows_episode_idx ON semantic_windows(episode_id);
CREATE INDEX semantic_windows_session_sequence_idx ON semantic_windows(session_id, sequence_no);
CREATE INDEX semantic_windows_cluster_idx ON semantic_windows(run_id, cluster_id);
CREATE INDEX semantic_windows_embedding_hnsw_idx ON semantic_windows USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

CREATE TABLE cluster_summaries (
    run_id bigint NOT NULL REFERENCES semantic_runs(id) ON DELETE CASCADE,
    cluster_id integer NOT NULL,
    label text,
    keywords_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    window_count bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (run_id, cluster_id)
);

CREATE TABLE labels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    color text NOT NULL DEFAULT '#64748b',
    description text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE annotations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type text NOT NULL,
    target_key text NOT NULL,
    label_id bigint REFERENCES labels(id) ON DELETE SET NULL,
    note text,
    review_state text NOT NULL DEFAULT 'unreviewed',
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE NULLS NOT DISTINCT (target_type, target_key, label_id)
);

CREATE INDEX annotations_target_idx ON annotations(target_type, target_key);

CREATE TABLE timesheet_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_key text NOT NULL UNIQUE,
    corpus_fingerprint text NOT NULL,
    cutoff timestamptz NOT NULL,
    algorithm_version integer NOT NULL,
    timezone text NOT NULL DEFAULT 'UTC',
    status text NOT NULL CHECK (status IN ('building', 'complete', 'failed')),
    ambiguity_count bigint NOT NULL DEFAULT 0,
    interval_count bigint NOT NULL DEFAULT 0,
    total_seconds bigint NOT NULL DEFAULT 0,
    generated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at timestamptz,
    error text
);

CREATE TABLE work_intervals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id bigint NOT NULL REFERENCES timesheet_snapshots(id) ON DELETE CASCADE,
    contributor_id bigint REFERENCES contributors(id),
    project_id bigint REFERENCES projects(id),
    activity_id bigint REFERENCES activities(id),
    local_date date NOT NULL,
    started_at timestamptz NOT NULL,
    ended_at timestamptz NOT NULL,
    exact_seconds bigint NOT NULL,
    ambiguous boolean NOT NULL DEFAULT false,
    ambiguity_reason text,
    evidence_count bigint NOT NULL DEFAULT 0,
    CHECK (started_at <= ended_at),
    CHECK (exact_seconds >= 0),
    UNIQUE (snapshot_id, contributor_id, started_at, ended_at, project_id, activity_id)
);

CREATE INDEX work_intervals_filter_idx ON work_intervals(snapshot_id, local_date, contributor_id, project_id, activity_id);

CREATE TABLE work_interval_evidence (
    interval_id bigint NOT NULL REFERENCES work_intervals(id) ON DELETE CASCADE,
    event_id bigint REFERENCES events(id),
    episode_key text,
    PRIMARY KEY (interval_id, event_id)
);

CREATE TABLE export_manifests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id bigint NOT NULL REFERENCES timesheet_snapshots(id),
    format text NOT NULL,
    filters_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    content_sha256 text NOT NULL,
    manifest_sha256 text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE OR REPLACE FUNCTION is_actionable_error_signature(value text)
RETURNS integer
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURN CASE
    WHEN value IS NULL THEN 0
    WHEN value ~* '^(fatal|panic|failed|failure|error|exception|traceback|assertionerror|FAILED)(:|\\s|$)' THEN 1
    WHEN value ~* '(command|process).*(exited|failed).*(code|status) [1-9][0-9]*' THEN 1
    ELSE 0
END;

CREATE OR REPLACE FUNCTION is_reportable_error_signature(value text)
RETURNS integer
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURN is_actionable_error_signature(value);

INSERT INTO labels(name, color, description) VALUES
    ('failure', '#ef4444', 'An attempt that failed or regressed'),
    ('blind-spot', '#f97316', 'A missed assumption, constraint, or evidence source'),
    ('repeated-attempt', '#eab308', 'A materially repeated approach'),
    ('resolved', '#22c55e', 'A problem with a validated resolution'),
    ('needs-review', '#3b82f6', 'Evidence requiring human review'),
    ('false-positive', '#94a3b8', 'A suspected pattern that is not meaningful')
ON CONFLICT (name) DO NOTHING;

INSERT INTO schema_meta(key, value) VALUES ('schema_version', '1')
ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value;
