CREATE TABLE resume_surface_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key text NOT NULL UNIQUE,
    model_name text NOT NULL,
    prompt_version text NOT NULL,
    selection_days integer NOT NULL,
    selection_limit integer NOT NULL,
    per_project_limit integer NOT NULL,
    selected_count integer NOT NULL DEFAULT 0,
    generated_count integer NOT NULL DEFAULT 0,
    reused_count integer NOT NULL DEFAULT 0,
    skipped_count integer NOT NULL DEFAULT 0,
    failed_count integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'running',
    error text,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at timestamptz,
    CHECK (selection_days > 0),
    CHECK (selection_limit > 0),
    CHECK (per_project_limit > 0),
    CHECK (status IN ('running', 'complete', 'partial', 'failed'))
);

CREATE INDEX resume_surface_runs_started_idx
ON resume_surface_runs(started_at DESC);

CREATE TABLE resume_surfaces (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surface_key text NOT NULL UNIQUE,
    run_id bigint NOT NULL REFERENCES resume_surface_runs(id) ON DELETE RESTRICT,
    root_session_id bigint NOT NULL UNIQUE REFERENCES sessions(id) ON DELETE CASCADE,
    project_id bigint REFERENCES projects(id) ON DELETE SET NULL,
    evidence_fingerprint text NOT NULL,
    prompt_hash text NOT NULL,
    prompt_version text NOT NULL,
    model_name text NOT NULL,
    concept text NOT NULL,
    long_term_goal text NOT NULL,
    summary text NOT NULL,
    current_state text NOT NULL,
    next_decision text,
    next_moves_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    research_directions_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    open_loops_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    confidence text NOT NULL,
    last_activity_at timestamptz NOT NULL,
    source_event_count bigint NOT NULL,
    source_max_event_id bigint NOT NULL,
    generated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (current_state IN ('ready', 'decision', 'blocked', 'waiting', 'done', 'unclear')),
    CHECK (confidence IN ('low', 'medium', 'high')),
    CHECK (source_event_count >= 0),
    CHECK (source_max_event_id >= 0),
    CHECK (jsonb_typeof(next_moves_json) = 'array'),
    CHECK (jsonb_typeof(research_directions_json) = 'array'),
    CHECK (jsonb_typeof(open_loops_json) = 'array')
);

CREATE INDEX resume_surfaces_activity_idx
ON resume_surfaces(last_activity_at DESC, id DESC);

CREATE INDEX resume_surfaces_state_activity_idx
ON resume_surfaces(current_state, last_activity_at DESC);

CREATE INDEX resume_surfaces_project_activity_idx
ON resume_surfaces(project_id, last_activity_at DESC);

CREATE TABLE resume_surface_sessions (
    surface_id bigint NOT NULL REFERENCES resume_surfaces(id) ON DELETE CASCADE,
    session_id bigint NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    position integer NOT NULL,
    PRIMARY KEY (surface_id, session_id),
    UNIQUE (surface_id, position),
    CHECK (position >= 0)
);

CREATE INDEX resume_surface_sessions_session_idx
ON resume_surface_sessions(session_id, surface_id);
