-- Additive compatibility migration: predecessor archives already have these tables.
CREATE TABLE IF NOT EXISTS timesheet_evidence_sets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint text NOT NULL UNIQUE,
    member_count bigint NOT NULL CHECK (member_count >= 0)
);
CREATE TABLE IF NOT EXISTS timesheet_evidence_members (
    evidence_set_id bigint NOT NULL REFERENCES timesheet_evidence_sets(id),
    event_id bigint NOT NULL REFERENCES events(id),
    episode_key text,
    PRIMARY KEY (evidence_set_id, event_id)
);
ALTER TABLE work_intervals ADD COLUMN IF NOT EXISTS evidence_set_id bigint
    REFERENCES timesheet_evidence_sets(id);
ALTER TABLE timesheet_snapshots ADD COLUMN IF NOT EXISTS calculation_fingerprint text;
CREATE INDEX IF NOT EXISTS timesheet_evidence_members_event_idx
    ON timesheet_evidence_members(event_id);
CREATE INDEX IF NOT EXISTS work_intervals_evidence_set_idx ON work_intervals(evidence_set_id);
DO $$
DECLARE spec record;
BEGIN
    FOR spec IN SELECT * FROM (VALUES
        ('timesheet_evidence_sets','id','bigint'),
        ('timesheet_evidence_sets','fingerprint','text'),
        ('timesheet_evidence_sets','member_count','bigint'),
        ('timesheet_evidence_members','evidence_set_id','bigint'),
        ('timesheet_evidence_members','event_id','bigint'),
        ('timesheet_evidence_members','episode_key','text'),
        ('work_intervals','evidence_set_id','bigint')
    ) AS required(relation, attribute, datatype)
    LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_attribute
            WHERE attrelid=to_regclass(spec.relation) AND attname=spec.attribute
              AND atttypid=spec.datatype::regtype AND NOT attisdropped) THEN
            RAISE EXCEPTION 'Incompatible shared evidence column %.%', spec.relation,spec.attribute;
        END IF;
    END LOOP;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE
        conrelid='timesheet_evidence_members'::regclass AND contype='p'
        AND pg_get_constraintdef(oid)='PRIMARY KEY (evidence_set_id, event_id)') THEN
        RAISE EXCEPTION 'Incompatible shared evidence primary key';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
        WHERE conrelid='timesheet_evidence_sets'::regclass AND contype='u'
          AND pg_get_constraintdef(oid)='UNIQUE (fingerprint)') THEN
        RAISE EXCEPTION 'Incompatible shared evidence fingerprint uniqueness';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
        WHERE conrelid='timesheet_evidence_members'::regclass AND contype='f'
          AND confrelid='events'::regclass)
       OR NOT EXISTS (SELECT 1 FROM pg_constraint
        WHERE conrelid='timesheet_evidence_members'::regclass AND contype='f'
          AND confrelid='timesheet_evidence_sets'::regclass)
       OR NOT EXISTS (SELECT 1 FROM pg_constraint
        WHERE conrelid='work_intervals'::regclass AND contype='f'
          AND confrelid='timesheet_evidence_sets'::regclass) THEN
        RAISE EXCEPTION 'Incompatible shared evidence foreign keys';
    END IF;
END $$;
CREATE OR REPLACE VIEW effective_work_interval_evidence AS
    SELECT interval.id AS interval_id, member.event_id, member.episode_key
    FROM work_intervals interval
    JOIN timesheet_evidence_members member ON member.evidence_set_id=interval.evidence_set_id
    UNION ALL
    SELECT evidence.interval_id,evidence.event_id,evidence.episode_key
    FROM work_interval_evidence evidence JOIN work_intervals interval ON interval.id=evidence.interval_id
    WHERE interval.evidence_set_id IS NULL;
CREATE TABLE storage_maintenance_progress (
    operation text PRIMARY KEY,
    last_interval_id bigint NOT NULL DEFAULT 0,
    intervals_verified bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE storage_interval_verification (
    interval_id bigint PRIMARY KEY REFERENCES work_intervals(id) ON DELETE CASCADE,
    evidence_set_id bigint NOT NULL REFERENCES timesheet_evidence_sets(id),
    member_count bigint NOT NULL
);
CREATE FUNCTION invalidate_interval_storage_proof() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_TABLE_NAME='work_interval_evidence' THEN
        IF TG_OP<>'INSERT' THEN
            DELETE FROM storage_interval_verification WHERE interval_id=OLD.interval_id;
        END IF;
        IF TG_OP<>'DELETE' THEN
            DELETE FROM storage_interval_verification WHERE interval_id=NEW.interval_id;
        END IF;
    ELSE
        IF OLD.evidence_set_id IS DISTINCT FROM NEW.evidence_set_id
            OR OLD.evidence_count IS DISTINCT FROM NEW.evidence_count THEN
            DELETE FROM storage_interval_verification WHERE interval_id=NEW.id;
        END IF;
    END IF;
    RETURN NULL;
END $$;
CREATE TRIGGER storage_legacy_proof_invalidation AFTER INSERT OR UPDATE OR DELETE
    ON work_interval_evidence FOR EACH ROW EXECUTE FUNCTION invalidate_interval_storage_proof();
CREATE TRIGGER storage_interval_proof_invalidation AFTER UPDATE ON work_intervals
    FOR EACH ROW EXECUTE FUNCTION invalidate_interval_storage_proof();
CREATE FUNCTION protect_referenced_evidence_members() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target bigint;
BEGIN
    IF TG_OP<>'INSERT' THEN
        target := OLD.evidence_set_id;
        IF EXISTS (SELECT 1 FROM work_intervals WHERE evidence_set_id=target) THEN
            RAISE EXCEPTION 'Referenced evidence set % is immutable',target;
        END IF;
    END IF;
    IF TG_OP<>'DELETE' THEN
        target := NEW.evidence_set_id;
        IF EXISTS (SELECT 1 FROM work_intervals WHERE evidence_set_id=target) THEN
            RAISE EXCEPTION 'Referenced evidence set % is immutable',target;
        END IF;
        RETURN NEW;
    END IF;
    RETURN OLD;
END $$;
CREATE TRIGGER immutable_referenced_evidence BEFORE INSERT OR UPDATE OR DELETE
    ON timesheet_evidence_members FOR EACH ROW EXECUTE FUNCTION protect_referenced_evidence_members();
